version: "3"

services:
  application:
    build:
      context: ../application
      dockerfile: application.prod.Dockerfile
    container_name: countive-docker-dev-application
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"
        reservations:
          cpus: "0.25"
          memory: "250M"
    environment:
      DATABASE_URI: ${DATABASE_URI}
      NEXT_AUTH_JS_JWT_SECRET: ${NEXT_AUTH_JS_JWT_SECRET}
      NEXT_AUTH_JS_SECRET: ${NEXT_AUTH_JS_SECRET}
      PORT: 3003
    networks:
      - countive-docker-dev-network
    ports:
      - "3000:3000"
      - "3003:3003"
    restart: on-failure:1
    volumes:
      - type: bind
        source: ../application
        target: /app
      - type: volume
        source: next_distribution
        target: /app/.next
      - type: volume
        source: node_modules
        target: /app/node_modules
  database:
    container_name: countive-docker-dev-database
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "500M"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
    image: "postgres:alpine"
    networks:
      - countive-docker-dev-network
    ports:
      - "5432:5432"
    restart: on-failure:1
    volumes:
      - type: bind
        source: ../database
        target: /var/lib/postgres/data

networks:
  countive-docker-dev-network:

volumes:
  node_modules:
  next_distribution:
