services:
  application:
    build:
      context: ../application
      dockerfile: application.dev.Dockerfile
    container_name: countive-docker-dev-application
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"
        reservations:
          cpus: "0.5"
          memory: "1G"
    environment:
      DATABASE_URI: ${DATABASE_URI}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      NEXT_AUTH_JS_JWT_SECRET: ${NEXT_AUTH_JS_JWT_SECRET}
      NEXT_AUTH_JS_SECRET: ${NEXT_AUTH_JS_SECRET}
      PORT: 3003
    networks:
      - countive-docker-dev-network
    ports:
      - "3000:3000"
      - "3003:3003"
    restart: on-failure:1
    volumes:
      - type: bind
        source: ../application
        target: /app
      - type: volume
        source: countive-docker-dev-next_distribution-volume
        target: /app/.next
      - type: volume
        source: countive-docker-dev-node_modules-volume
        target: /app/node_modules
  database:
    container_name: countive-docker-dev-database
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "500M"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
    image: "postgres:alpine"
    networks:
      - countive-docker-dev-network
    ports:
      - "5432:5432"
    restart: on-failure:1
    volumes:
      - type: volume
        source: countive-docker-dev-postgres_data-volume
        target: /var/lib/postgres/data
  migrate:
    build:
      context: ../application
      dockerfile: application.dev.Dockerfile
    command: ["npx", "prisma", "migrate", "dev"]
    container_name: countive-docker-dev-migrate
    depends_on:
      - database
    environment:
      DATABASE_URI: ${DATABASE_URI}
    networks:
      - countive-docker-dev-network
    profiles:
      - migrate
    volumes:
      - type: bind
        source: ../application/prisma
        target: /app/prisma
      - type: volume
        source: countive-docker-dev-node_modules-volume
        target: /app/node_modules
  seed:
    build:
      context: ../application
      dockerfile: application.dev.Dockerfile
    command: ["npx", "prisma", "db", "seed"]
    container_name: countive-docker-dev-seed
    depends_on:
      - database
    environment:
      DATABASE_URI: ${DATABASE_URI}
    networks:
      - countive-docker-dev-network
    profiles:
      - seed
    volumes:
      - type: bind
        source: ../application/prisma
        target: /app/prisma
      - type: volume
        source: countive-docker-dev-node_modules-volume
        target: /app/node_modules

networks:
  countive-docker-dev-network:

volumes:
  countive-docker-dev-node_modules-volume:
  countive-docker-dev-next_distribution-volume:
  countive-docker-dev-postgres_data-volume:
